[encoder]
alpha = 1
block_size = 3
level = 2
wavelet = "haar"
coefficients = ["ad", "da", "dd"]
color_space = "YCrCb"
use_channels = [1, 2]

[gui]
zoom_in_factor = 1.25
zoom_out_factor = 0.8
scroll_step = 0.5
image_formats = "Images (*.png *.jpg *.jpeg *.bmp)"
